name: ERPY
options:
  bundleIdPrefix: de.stevenpetersen
targets:
  ERPY:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources]
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: de.stevenpetersen.ERPY
        MARKETING_VERSION: 2.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
